### PR TITLE
Fix sirupsen logrus

### PR DESCRIPTION
**Pull request by UnderGreen**

### CODE REVIEW

**Comment by eldios** [comment]
Sergei, unless I'm mistaken I'm seeing that besides fixing sirupsen you also upgraded Go to 1.9
If I'm seeing it right, that should be split in a different commit to minimize the amount of changes.

Testing 17K lines just by looking at the changes would be hard :/

**Comment by UnderGreen** [comment]
I have not changed go version. If you mean Godeps value, that just a value of my local go version. We build stolon inside container and there still old Golang version.

**Comment by eldios** [comment]
yes I was referring to the Godeps.json file but now I'm seeing a lot of other changes.
If you try running:
```
$ git checkout sergei/fix_sirupsen_logrus && git diff master
```
You'll see that there's a lot of unrelated changes in there, mostly found in:
* /vendor/github.com/gravitational/trace/
* /vendor/golang.org/x/

There's also a lot of new GoDeps added. Did you unintentionally commit all the changed files after locally upgrading?

**Comment by UnderGreen** [comment]
I've manually updated only our trace package. It cannot affect stolon apps. Utilities in `golang/x` was added/updated by new `sirupsen/logrus` version. And again they can affect only logging output. + I have installed cluster with that changes and work with them to test my `stolonctl` tool. Nothing happens, works as expected.

**Comment by eldios** [comment]
What I'm saying, and I may be wrong, is that changes that are not related to the commit title/subject should NOT be included.

If the `golang/x` are needed by the change then fine but the others should not be committed, I think.

I'm no expert in branching and code management though, so maybe this approach is too picky.
Maybe Sasha, Roman or Dmitry would be better to decide if we should pass/include little unrelated changes if they're harmless or keep creating different PRs for every little set of changes, grouped by "rational scope".

**Pull request closed without merging**
